# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreatSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  
  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'

  target 'GreatSDKTests' do
    # Pods for testing
  end

end
